# Generated by Django 4.1.3 on 2023-05-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0002_parking_parkingspot_reservation_delete_parkingspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_id', models.CharField(max_length=10, unique=True)),
                ('is_vacant', models.BooleanField(default=True)),
                ('distance_from_root', models.IntegerField()),
            ],
        ),
    ]
