# Generated by Django 4.1.3 on 2023-05-10 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0003_parkingspace'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParkingSpace',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='parking_spot',
        ),
        migrations.DeleteModel(
            name='ParkingSpot',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
