# Generated by Django 4.1.3 on 2023-05-10 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0005_parkingspace_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.CharField(max_length=50, unique=True)),
                ('is_vacant', models.BooleanField(default=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_app.parkingspace')),
            ],
        ),
    ]
